/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CityRouteImport } from './routes/city'
import { Route as FerryRouteImport } from './routes/ferry'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as NightRouteImport } from './routes/night'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as RunRouteImport } from './routes/run'
import { Route as YiRouteImport } from './routes/yi'
import { Route as PeopleIdRouteImport } from './routes/people.$id'
import { Route as StallIdRouteImport } from './routes/stall.$id'
import { Route as YiBookRouteImport } from './routes/yi_.book'
import { Route as YiCastRouteImport } from './routes/yi_.cast'
import { Route as YiVoyageRouteImport } from './routes/yi_.voyage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityRoute = CityRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => rootRouteImport,
} as any)
const FerryRoute = FerryRouteImport.update({
  id: '/ferry',
  path: '/ferry',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const NightRoute = NightRouteImport.update({
  id: '/night',
  path: '/night',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoute = RunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => rootRouteImport,
} as any)
const YiRoute = YiRouteImport.update({
  id: '/yi',
  path: '/yi',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PeopleRoute,
} as any)
const StallIdRoute = StallIdRouteImport.update({
  id: '/stall/$id',
  path: '/stall/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const YiBookRoute = YiBookRouteImport.update({
  id: '/yi_/book',
  path: '/yi/book',
  getParentRoute: () => rootRouteImport,
} as any)
const YiCastRoute = YiCastRouteImport.update({
  id: '/yi_/cast',
  path: '/yi/cast',
  getParentRoute: () => rootRouteImport,
} as any)
const YiVoyageRoute = YiVoyageRouteImport.update({
  id: '/yi_/voyage',
  path: '/yi/voyage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/city': typeof CityRoute
  '/ferry': typeof FerryRoute
  '/journal': typeof JournalRoute
  '/night': typeof NightRoute
  '/people': typeof PeopleRouteWithChildren
  '/run': typeof RunRoute
  '/yi': typeof YiRoute
  '/people/$id': typeof PeopleIdRoute
  '/stall/$id': typeof StallIdRoute
  '/yi/book': typeof YiBookRoute
  '/yi/cast': typeof YiCastRoute
  '/yi/voyage': typeof YiVoyageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/city': typeof CityRoute
  '/ferry': typeof FerryRoute
  '/journal': typeof JournalRoute
  '/night': typeof NightRoute
  '/people': typeof PeopleRouteWithChildren
  '/run': typeof RunRoute
  '/yi': typeof YiRoute
  '/people/$id': typeof PeopleIdRoute
  '/stall/$id': typeof StallIdRoute
  '/yi/book': typeof YiBookRoute
  '/yi/cast': typeof YiCastRoute
  '/yi/voyage': typeof YiVoyageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/city': typeof CityRoute
  '/ferry': typeof FerryRoute
  '/journal': typeof JournalRoute
  '/night': typeof NightRoute
  '/people': typeof PeopleRouteWithChildren
  '/run': typeof RunRoute
  '/yi': typeof YiRoute
  '/people/$id': typeof PeopleIdRoute
  '/stall/$id': typeof StallIdRoute
  '/yi_/book': typeof YiBookRoute
  '/yi_/cast': typeof YiCastRoute
  '/yi_/voyage': typeof YiVoyageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/city'
    | '/ferry'
    | '/journal'
    | '/night'
    | '/people'
    | '/run'
    | '/yi'
    | '/people/$id'
    | '/stall/$id'
    | '/yi/book'
    | '/yi/cast'
    | '/yi/voyage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/city'
    | '/ferry'
    | '/journal'
    | '/night'
    | '/people'
    | '/run'
    | '/yi'
    | '/people/$id'
    | '/stall/$id'
    | '/yi/book'
    | '/yi/cast'
    | '/yi/voyage'
  id:
    | '__root__'
    | '/'
    | '/city'
    | '/ferry'
    | '/journal'
    | '/night'
    | '/people'
    | '/run'
    | '/yi'
    | '/people/$id'
    | '/stall/$id'
    | '/yi_/book'
    | '/yi_/cast'
    | '/yi_/voyage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityRoute: typeof CityRoute
  FerryRoute: typeof FerryRoute
  JournalRoute: typeof JournalRoute
  NightRoute: typeof NightRoute
  PeopleRoute: typeof PeopleRouteWithChildren
  RunRoute: typeof RunRoute
  YiRoute: typeof YiRoute
  StallIdRoute: typeof StallIdRoute
  YiBookRoute: typeof YiBookRoute
  YiCastRoute: typeof YiCastRoute
  YiVoyageRoute: typeof YiVoyageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city': {
      id: '/city'
      path: '/city'
      fullPath: '/city'
      preLoaderRoute: typeof CityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferry': {
      id: '/ferry'
      path: '/ferry'
      fullPath: '/ferry'
      preLoaderRoute: typeof FerryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/night': {
      id: '/night'
      path: '/night'
      fullPath: '/night'
      preLoaderRoute: typeof NightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run': {
      id: '/run'
      path: '/run'
      fullPath: '/run'
      preLoaderRoute: typeof RunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yi': {
      id: '/yi'
      path: '/yi'
      fullPath: '/yi'
      preLoaderRoute: typeof YiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof PeopleRoute
    }
    '/stall/$id': {
      id: '/stall/$id'
      path: '/stall/$id'
      fullPath: '/stall/$id'
      preLoaderRoute: typeof StallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yi_/book': {
      id: '/yi_/book'
      path: '/yi/book'
      fullPath: '/yi/book'
      preLoaderRoute: typeof YiBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yi_/cast': {
      id: '/yi_/cast'
      path: '/yi/cast'
      fullPath: '/yi/cast'
      preLoaderRoute: typeof YiCastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yi_/voyage': {
      id: '/yi_/voyage'
      path: '/yi/voyage'
      fullPath: '/yi/voyage'
      preLoaderRoute: typeof YiVoyageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PeopleRouteChildren {
  PeopleIdRoute: typeof PeopleIdRoute
}

const PeopleRouteChildren: PeopleRouteChildren = {
  PeopleIdRoute: PeopleIdRoute,
}

const PeopleRouteWithChildren =
  PeopleRoute._addFileChildren(PeopleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityRoute: CityRoute,
  FerryRoute: FerryRoute,
  JournalRoute: JournalRoute,
  NightRoute: NightRoute,
  PeopleRoute: PeopleRouteWithChildren,
  RunRoute: RunRoute,
  YiRoute: YiRoute,
  StallIdRoute: StallIdRoute,
  YiBookRoute: YiBookRoute,
  YiCastRoute: YiCastRoute,
  YiVoyageRoute: YiVoyageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
